<%@ Page Title="Containers" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Containers.aspx.cs" Inherits="lab7.Containers.Contaiers" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="ContainersGridView"
            AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="ContainersGridView_RowCancelingEdit"
            OnRowDeleting="ContainersGridView_RowDeleting"
            OnRowEditing="ContainersGridView_RowEditing" 
            OnRowUpdating="ContainersGridView_RowUpdating" 
            OnPageIndexChanging="ContainersGridView_PageIndexChanging"
            Caption="Containers" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4">
            <Columns>
                <asp:BoundField DataField="ContainerId" HeaderText="Id" SortExpression="ContainerId" ReadOnly="true" />    
                <asp:BoundField DataField="Number" HeaderText="number" SortExpression="Number" />
                <asp:BoundField DataField="TankCapacity" HeaderText="tankCapacity" SortExpression="TankCapacity" />
            </Columns>
            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#330099" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <SortedAscendingCellStyle BackColor="#FEFCEB" />
            <SortedAscendingHeaderStyle BackColor="#AF0101" />
            <SortedDescendingCellStyle BackColor="#F6F0C0" />
            <SortedDescendingHeaderStyle BackColor="#7E0000" />
        </asp:GridView>

    </div>
    
    <div style="margin-top: 10px;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
        <h2>Add container</h2>

        <div>
            <span>Number: </span>
            <asp:TextBox ID="ContainersNumberTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>TankCapacity: </span>
            <asp:TextBox ID="ContainersTankCapacityTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="AddContainersButton" runat="server" Text="Add container" OnClick="AddContainersButton_Click" />
        </div>
    </div>
    
</asp:Content>