<%@ Page Title="IncomeAndExpensesOfGsms" MasterPageFile="~/Site.Master" Language="C#" AutoEventWireup="true" CodeBehind="IncomeAndExpensesOfGsms.aspx.cs" Inherits="lab7.IncomeAndExpensesOfGsms.IncomeAndExpensesOfGsms" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="IncomeAndExpensesOfGsmsGridView"
            AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="IncomeAndExpensesOfGsmsGridView_RowCancelingEdit"
            OnRowDeleting="IncomeAndExpensesOfGsmsGridView_RowDeleting"
            OnRowEditing="IncomeAndExpensesOfGsmsGridView_RowEditing"
            OnRowUpdating="IncomeAndExpensesOfGsmsGridView_RowUpdating" 
            OnPageIndexChanging="IncomeAndExpensesOfGsmsGridView_PageIndexChanging"
            Caption="IncomeAndExpensesOfGsms" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4">
            <Columns>
                <asp:BoundField DataField="IncomeAndExpenseOfGsmid" HeaderText="Id" SortExpression="IncomeAndExpenseOfGsmid" ReadOnly="true" />    
                <asp:BoundField DataField="NumberOfCapacity" HeaderText="numberOfCapacity" SortExpression="NumberOfCapacity" />
                <asp:BoundField DataField="IncomeOrExpensePerliter" HeaderText="incomeOrExpensePerliter" SortExpression="IncomeOrExpensePerliter" />
                
                <asp:TemplateField HeaderText="Containers" SortExpression="Containers.Number">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ContainersDropDownList" DataSourceID="ContainersSqlDataSource" DataValueField="ContainerId" DataTextField="Number" runat="server"  SelectedValue='<%# Bind("ContainerId") %>'></asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="ContainerId" runat="server" Text='<%# Eval("Container.Number") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="DateAndTimeOfTheOperationIncomeOrExpense" SortExpression="IncomeAndExpensesOfGsms.DateAndTimeOfTheOperationIncomeOrExpense">
                    <EditItemTemplate>
                        <asp:Calendar ID="ReleaseDateCalendar" runat="server" SelectedDate='<%# Bind("DateAndTimeOfTheOperationIncomeOrExpense") %>'></asp:Calendar>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="DateAndTimeOfTheOperationIncomeOrExpense" runat="server" Text='<%# Eval("DateAndTimeOfTheOperationIncomeOrExpense") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:BoundField DataField="ResponsibleForTheOperation" HeaderText="responsibleForTheOperation" SortExpression="ResponsibleForTheOperation" />

            </Columns>
            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#330099" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <SortedAscendingCellStyle BackColor="#FEFCEB" />
            <SortedAscendingHeaderStyle BackColor="#AF0101" />
            <SortedDescendingCellStyle BackColor="#F6F0C0" />
            <SortedDescendingHeaderStyle BackColor="#7E0000" />
        </asp:GridView>

    </div>
   
    <div style="position:relative;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
       
        <h2>Add IncomeAndExpensesOfGsms</h2>

        <div>
            <span>NumberOfCapacity: </span>
            <asp:TextBox ID="IncomeAndExpensesOfGsmsNumberOfCapacityTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>DateAndTimeOfTheOperationIncomeOrExpense: </span>
            <asp:Calendar ID="IncomeAndExpensesOfGsmsDateAndTimeOfTheOperationIncomeOrExpenseTextBox" runat="server" BackColor="#FFFFCC" BorderColor="#FFCC66" BorderWidth="1px" DayNameFormat="Shortest" Font-Names="Verdana" Font-Size="8pt" ForeColor="#663399" Height="200px" ShowGridLines="True" Width="220px">
                <DayHeaderStyle BackColor="#FFCC66" Font-Bold="True" Height="1px" />
                <NextPrevStyle Font-Size="9pt" ForeColor="#FFFFCC" />
                <OtherMonthDayStyle ForeColor="#CC9966" />
                <SelectedDayStyle BackColor="#CCCCFF" Font-Bold="True" />
                <SelectorStyle BackColor="#FFCC66" />
                <TitleStyle BackColor="#990000" Font-Bold="True" Font-Size="9pt" ForeColor="#FFFFCC" />
                <TodayDayStyle BackColor="#FFCC66" ForeColor="White" />
            </asp:Calendar>
        </div>

        <div>
            <span>IncomeOrExpensePerliter: </span>
            <asp:TextBox ID="IncomeAndExpensesOfGsmsIncomeOrExpensePerliterTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>ResponsibleForTheOperation: </span>
            <asp:TextBox ID="IncomeAndExpensesOfGsmsResponsibleForTheOperationTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Containers: </span>
            <asp:DropDownList ID="IncomeAndExpensesOfGsmsDropDownList1" DataSourceID="ContainersSqlDataSource" DataValueField="ContainerId" DataTextField="Number" runat="server"></asp:DropDownList>
        </div>

        <div>
            <asp:Button ID="AddButton" runat="server" Text="Add IncomeAndExpensesOfGsms" OnClick="AddButton_Click" />
        </div>
       
    </div>
    
    <asp:SqlDataSource ID="ContainersSqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings: gsmConnectionString %>" 
        SelectCommand="SELECT [ContainerId], [Number] FROM [Containers]">
    </asp:SqlDataSource>
</asp:Content>