<%@ Page Title="Gsm" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="GSM.aspx.cs" Inherits="lab7.GSM.GSM" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="GsmGridView"
            AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GsmGridView_RowCancelingEdit"
            OnRowDeleting="GsmGridView_RowDeleting"
            OnRowEditing="GsmGridView_RowEditing" 
            OnRowUpdating="GsmGridView_RowUpdating" 
            OnPageIndexChanging="GSMGridView_PageIndexChanging"
            Caption="Gsm" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" BackColor="White" BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4">
            <Columns>
                <asp:BoundField DataField="gSMId" HeaderText="Id" SortExpression="gSMId" ReadOnly="true" />    
                <asp:BoundField DataField="typeOfGSM" HeaderText="typeOfGSM" SortExpression="typeOfGSM" />
                <asp:BoundField DataField="tTKOfType" HeaderText="tTKOfType" SortExpression="tTKOfType" />
            </Columns>
            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <RowStyle BackColor="White" ForeColor="#330099" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <SortedAscendingCellStyle BackColor="#FEFCEB" />
            <SortedAscendingHeaderStyle BackColor="#AF0101" />
            <SortedDescendingCellStyle BackColor="#F6F0C0" />
            <SortedDescendingHeaderStyle BackColor="#7E0000" />
        </asp:GridView>

    </div>
    
    <div style="margin-top: 10px;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
        <h2>Add gsm</h2>

        <div>
            <span>typeOfGSM: </span>
            <asp:TextBox ID="GsmtypeOfGSMTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>tTKOfType: </span>
            <asp:TextBox ID="GsmtTKOfTypeTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="AddGsmButton" runat="server" Text="Add gsm" OnClick="AddGsmButton_Click" />
        </div>
    </div>
    
</asp:Content>